### ISSUE TITLE
Fine-tune features

### ISSUE THREAD

**Issue by jayjay19630** [AY2425S1-CS2103T-W10-2/tp#141]
Create enhancements for any existing features. Currently these features include but are not limited to:
- [x] Finding person with multiple arguments
- [x] Having two separate tables for person and appointments for better visibility

Add more if necessary.

**Comment by zaidansani** [comment]
@jayjay19630 has this been resolved? I believe we have merged the PRs relevant to this

**Comment by jayjay19630** [comment]
> @jayjay19630 has this been resolved? I believe we have merged the PRs relevant to this

Looks like it, I'll close this now!
