### ISSUE TITLE
[Add AFTER PE-D] Update DG: Appendix: Planned Enhancements

### ISSUE THREAD

**Issue by rxchell** [AY2425S1-CS2103T-W10-2/tp#147]
- to counter known feature flaws that you are not allowed to fix in v1.6.
- This can be added after the PE-D is over (and PE-D bug reports have been received).
- This section may contain up to team_size x 2 enhancements e.g., a 5-person team can have up to 10 enhancements.
-At the start of the section, clearly state the team size. While this information is not useful for a real DG, it will help PE testers easily see if you have exceeded the allowed planned enhancements count.
- For a similar reason, structure this section as a numbered list, each item in the list describing exactly one planned enhancement.
- Each enhancement should be specific, describing the feature flaw it addresses and how exactly the feature will be changed, providing sample UIs/inputs/outputs if applicable.

**Comment by jayjay19630** [comment]
Resolved
