### ISSUE TITLE
Clean Up UI

### ISSUE THREAD

**Issue by jayjay19630** [AY2425S1-CS2103T-W10-2/tp#197]
Last checks to finalize UI
- [x] Add children statement somewhere that keeps readding the ui elements into the hbox
- [x] Make AID PID label white
- [x] Others (if necessary)

**Comment by choiwab** [comment]
> Last checks to finalize UI
> 
> * [ ]  Add children statement somewhere that keeps readding the ui elements into the hbox
> * [ ]  Make AID PID label white
> * [ ]  Others (if necessary)
+Make the person list panel and appointment list panel white after clear command (right now turns to grey background color)
